export const product =  [

    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"Childish Gambino",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },
    {
        id:1,
        Name:"A$AP Rosky",
        Email:"falcko@asapmob.com",
        Data:"03/20/2017",
        Record:"AT.LONG.LAST.A$AP",
        Lacation:"nYC,NY",
        Best:"L$D",
    },

]
export default product;

